#!/bin/bash
#

. $HOME/.config/admiral.d/config

volumeState=$(amixer get Master | grep \% | awk '{print $4}'| sed 's/[^0-9]//g')

# Determine volume icon depending on the level of volume.
if [[ ${volumeState} -eq 0 ]]; then
	volumeIcon=""
elif [[ ${volumeState} -le 50 ]]; then
	volumeIcon=""
else
	volumeIcon=""
fi

if ["$(amixer get Master | grep Mono: | cut -d\  -f8)" = "[off]"]; then
    volumeIcon=""
	volumeColor=${RED}
else
	volumeColor=${FG}
fi
	echo "%{F$volumeColor}${volumeIcon} %{F$FG}${volumeState}% "
